#pragma once
#ifndef __MAP_CONFIG__H_
#define __MAP_CONFIG__H_
#include <vector>
#include "cocos2d.h"

using namespace std;
typedef vector<vector<size_t>> Vector2_Size_t;
const size_t MAP_UTILE = 30; //地图单元格单元大小
const size_t MAP_ROW_NUMBER = 13;//地图单元个数
const size_t MAP_COLUMN_NUMBER = 15;
enum MAP_TYPE
{
	EMPTY,//空
	BOX,//箱子
	FLOOR,//地板
	PROPS,//道具
	PLAYER,//主角
	ENEMY,//敌人A
};
const Vector2_Size_t MAP_1 = {
	{FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR},
	{FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR},
	{FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR},
	{FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR},
	{FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR},
	{FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR},
	{FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR},
	{FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR},
	{FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR},
	{FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR},
	{FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR},
	{FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR},
	{FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR}
};
const Vector2_Size_t MAP_2 = {
	{FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR},
	{FLOOR, PLAYER, FLOOR, BOX, FLOOR, PROPS, BOX, EMPTY, PROPS, FLOOR, BOX, PROPS, BOX, ENEMY,FLOOR},
	{FLOOR, EMPTY, BOX, FLOOR, PROPS, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, FLOOR, BOX, EMPTY, FLOOR},
	{FLOOR, EMPTY, FLOOR, BOX, FLOOR, PROPS, BOX, EMPTY, FLOOR, PROPS, BOX, FLOOR, PROPS, EMPTY, FLOOR},
	{FLOOR, EMPTY, PROPS, FLOOR, EMPTY, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, BOX, EMPTY, EMPTY, FLOOR},
	{FLOOR, EMPTY, PROPS, FLOOR, PROPS, PROPS, FLOOR, EMPTY, BOX, BOX, EMPTY, PROPS, EMPTY, EMPTY, FLOOR},
	{FLOOR, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, FLOOR},
	{FLOOR, BOX, PROPS, PROPS, BOX, EMPTY, BOX, EMPTY, BOX, BOX, EMPTY, BOX, PROPS, EMPTY, FLOOR},
	{FLOOR, PROPS, FLOOR, PROPS, BOX, BOX, BOX, EMPTY, EMPTY, EMPTY, EMPTY, BOX, FLOOR, EMPTY, FLOOR},
	{FLOOR, BOX, BOX, FLOOR, BOX, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR},
	{FLOOR, PROPS, FLOOR, PROPS, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, EMPTY, EMPTY, EMPTY, FLOOR},
	{FLOOR, BOX, BOX, FLOOR, BOX, PROPS, BOX, EMPTY, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, ENEMY,FLOOR},
	{FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR}
};
const Vector2_Size_t MAP_3 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, ENEMY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_4 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_5 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_6 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_7 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_8 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_9 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_10 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_11 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_12 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_13 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_14 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_15 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }

};
const Vector2_Size_t MAP_16 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_17 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_18 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_19 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_20 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const Vector2_Size_t MAP_21 = {
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
	{ FLOOR, PLAYER, EMPTY, EMPTY, PROPS, EMPTY, BOX, BOX, EMPTY, EMPTY, BOX, PROPS, EMPTY, EMPTY,FLOOR },
	{ FLOOR, EMPTY, FLOOR, BOX, PROPS, BOX, PROPS, BOX, FLOOR, PROPS, BOX, PROPS, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, BOX, FLOOR },
	{ FLOOR, PROPS, FLOOR, FLOOR, BOX, PROPS, BOX, FLOOR, BOX, PROPS, BOX, FLOOR, PROPS, BOX, FLOOR },
	{ FLOOR, EMPTY, BOX, PROPS, PROPS, BOX, BOX, BOX, PROPS, BOX, BOX, BOX, PROPS, PROPS, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, PROPS, EMPTY, BOX, PROPS, BOX, EMPTY, BOX, EMPTY, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, PROPS, PROPS, BOX, FLOOR, BOX, BOX, BOX, BOX, EMPTY, BOX, EMPTY, BOX, FLOOR },
	{ FLOOR, EMPTY, FLOOR, FLOOR, EMPTY, BOX, BOX, EMPTY, FLOOR, FLOOR, PROPS, BOX, FLOOR, EMPTY, FLOOR },
	{ FLOOR, BOX, PROPS, BOX, BOX, FLOOR, PROPS, FLOOR, BOX, BOX, EMPTY, BOX, EMPTY, EMPTY, FLOOR },
	{ FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, FLOOR, EMPTY, BOX, PROPS, BOX, PROPS, FLOOR, EMPTY, FLOOR },
	{ FLOOR, EMPTY, PROPS, BOX, BOX, PROPS, PROPS, BOX, EMPTY, BOX, PROPS, EMPTY, EMPTY, ENEMY,FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
};
const vector<Vector2_Size_t> MAPS = {
	MAP_1,MAP_2, MAP_3,MAP_4,MAP_5,MAP_6,MAP_7,MAP_8,MAP_9,MAP_10,
	MAP_11,MAP_12, MAP_13,MAP_14,MAP_15,MAP_16,MAP_17,MAP_18,MAP_19,MAP_20 ,
	MAP_21
};
//关卡从1开始的，所以需要-1
inline Vector2_Size_t const getMap(size_t level) {
	size_t length = MAPS.size();
	if (0 == level || level > length)
	{
		CCLOG("(0 == level || level > length level = %d length = %d", level, length);
		return Vector2_Size_t();
	}
	return MAPS.at(level - 1);
}
#endif